name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or your preferred Node version

      - name: Install dependencies
        run: npm install
        # or use: run: yarn

      - name: Build
        run: npm run build
        # or run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
